config/routes.rb
Blog::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#index"
  resources :users do
    resources :posts do
      member { post :mercury_update }
      resources :comments
    end
  end
  resources :sessions
  resources :password_resets

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, :presence => true
  has_many :comments, :dependent => :destroy
  belongs_to :user
  scope :recent, order("created_at desc")
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  before_create { generate_token(:auth_token) }
  before_update { generate_token(:auth_token) }
  after_create :welcome_mail
  #before_save :admin
  
  validates :password, :presence => true, :length => {:minimum => 3}, :on => :create
  validates :email, :presence => true, :uniqueness => true, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}, :length => {:minimum => 6}
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
     self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  private
  
  def admin
    if self.id == 1
      self.is_admin = true
    end
  end
  
  def welcome_mail
    UserMailer.welcome(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    @comment.user_id = User.find_by_auth_token(cookies[:auth_token]).id
    if !@comment.save
      flash[:notice] = "Sorry, your comments need the body."
    else
      @count = @post.comments.count
    end
    respond_to do |format|
      format.html {redirect_to user_post_path(params[:user_id], params[:post_id])}
      format.js
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset 
      redirect_to root_url, :notice => "Email sent with password reset instructions."
    else
      redirect_to new_password_reset_path, :notice => "There's no user with this email."
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :get
  before_filter :check_auth, :only => [:edit, :update]
  before_filter :check_admin_auth, :only => :destroy
  
  def check_auth
    if @user && @user.id != @post.user_id
        flash[:notice] = "Sorry, you can't edit this post"
        redirect_to [@show_user, @post]    
     end
  end

  def check_admin_auth
    if @user.id != @post.user_id && !(@user.is_admin?)
      flash[:notice] = "Sorry, you can't edit this post"
      redirect_to [@show_user, @post] 
   end
  end

  def get
    @user = User.find_by_auth_token(cookies[:auth_token])
    @show_user = User.find(params[:user_id])
    if params[:id]
      @post = Post.find(params[:id])
    end
  end
  
  def index
    @posts = @show_user.posts.order("created_at desc").page(params[:page]).per_page(10)
  end
  
  def show
    @show_user = User.find(params[:user_id])
    @post = @show_user.posts.find(params[:id])
    @comments = @post.comments.all
    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def new
    @post = Post.new
    @post.user_id = @user.id
    
    respond_to do |format|
	format.html  #new.html.erb  
    end
  end

  def edit
    @post = @show_user.posts.find(params[:id])
  end
 
  def create
    @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@user, @post], notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to [@user, @post], notice: 'Post was successfully updated.' }
       
      else
        format.html { render action: "edit" }
       
      end
    end
  end

  def destroy
   
    @post = @show_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_url }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    if params[:remember_me]
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token
    end
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  cookies.delete(:auth_token)
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def new
    @user = User.new
  end

  def index
   @users = User.order("id").all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.posts.create(title: "Welcome", body: "Start writing right now!")
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  
  respond_to do |format|
      format.html { redirect_to users_url }
      format.js
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <div class="title">
      <h3><%= comment.title %></h3>
    </div> 
    <div class="body">
      <p><%= comment.body %></p>
      <p><b>by</b>
        <%= User.find(comment.user_id).email %> (<%= time_ago_in_words comment.created_at %> ago)
      </p>
    </div>
  <hr>
<% end %>

app/views/comments/create.js.erb
$("#comments").append("<%= escape_javascript(render(:partial => @comment)) %>");
$('div#<%= dom_id(@comment) %>').effect('highlight', {}, 3000);
$("#comments_count").replaceWith(function() {
  return "<div id='comments_count'><h3><%= pluralize(@count, 'Comment') %></h3></div>";
});
$('#new_comment').each (function(){
  this.reset();
});

app/views/comments/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag   "application" %>
  <%= javascript_include_tag "application" %>
  <%= yield :script %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
      $(document).ready(function() {
        $("#cleditor").cleditor({useCSS: true});
      });
  </script>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">AwesomeBlog v0.4</a>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="span3" style="text-align:center;">
			<% if current_user %>
				Logged in as <%= current_user.email %><br>
				<%= link_to "Log out", log_out_path %>
			<% else %>
				You still need to <%= link_to "log in", log_in_path %> or <%= link_to "sign up", sign_up_path %> to post something.
    
			<% end %>
		</div>
		<div class="span9" style="text-align:center;">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, id: "cleditor" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% if !(post.is_private?) %>
<div class="post">
    <h1><%= link_to post.title, [@show_user, post] %></h1>
    (posted <%= time_ago_in_words post.created_at %> ago)
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post.</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @post] %> |
<%= link_to 'Back', user_posts_path(params[:user_id]) %>

app/views/posts/index.html.erb
<div id="posts">
  <%= render @posts %>
</div>

<%= will_paginate @posts %>

<br />
<% if @user && @posts.first %>
 <% if @user.id == @posts.first.user_id %>>
   <%= link_to 'New Post', new_user_post_path( @user.id ) %>
 <% end %>
<% else if @user && @user.id == @show_user.id %>
  <%= link_to 'New Post', new_user_post_path( @user.id ) %>
<% end %>
<% end %>



<%= link_to 'Back', root_url %>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(params[:user_id]) %>

app/views/posts/show.html.erb
<div class="posts">
<h1>
  <span id="post_title">
    <%= raw @post.title %>
  </span>
</h1>

<div id="post_body">
    <%= raw @post.body %>
</div>

<div id="private_box" style="display:none;">
<!--
  <input id="is_private" name="is_private" type="checkbox" value="true" class="mercury-region" data-type="editable" checked="checked"/>Private?
  <input id="is_private" name="is_private" type="checkbox" value="true" class="mercury-region" data-type="editable" />Private? -->

  <% if @post.is_private? %>
    TODO: Сделать удобный метод, задающий приватность поста.
  <% else %>
    TODO: Сделать удобный метод, задающий приватность поста.
  <% end %>

</div>

<div id="links">
  <% if @user %>
    <%= link_to 'Edit', edit_user_post_path(@show_user, @post), id: "edit_link", data: {save_url: mercury_update_user_post_path(@show_user, @post)} %> |
    <%= link_to 'Destroy', [@show_user, @post], confirm: 'Are you sure?', method: :delete %> |
  <% end %>
  <%= link_to 'Back', user_posts_path(@show_user) %>
</div>
<hr>
</div>
<div id="comments">
<% if @comments.empty? %>
  <div id="comments_count">
    <h3>There's no comments yet</h3>
  </div>
<% else %>
  <div id="comments_count">
    <h3><%= pluralize(@comments.count, 'Comment') %></h3>
  </div>
    <%= render @comments %>

<% end %> 
</div> 


<% if cookies[:auth_token] %>
<div id="add_comments">
<h3 class="add">Add a comment:</h3>
<%= form_for([@show_user, @post, @post.comments.build], :remote => true) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">

    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<% end %>

app/views/users/destroy.js.erb
$('#<%= dom_id(@user) %>').fadeOut();

app/views/users/index.html.erb
<h2>Blogs:</h2>
<div id="users">
<% @users.each do |user| %>
 <%= div_for user do %>
    <p class="aligning">
    <%= link_to user.email, user_posts_path(user.id) %>
    <%= pluralize(user.posts.count, "post") %>
    <% if cookies[:auth_token] %>
     
        <% if User.find_by_auth_token(cookies[:auth_token]).is_admin? %>
          <%= link_to "Destroy", user, confirm: 'Are you sure?', method: :delete, remote: true if user.id > 1 %>
        <% end %>
      
    <% end %>
    </p>
  <% end %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>